const WebSocket = require("ws")

const deviceASocket = new WebSocket('ws://localhost:8080');
const deviceBSocket = new WebSocket('ws://localhost:8080');


deviceASocket.addEventListener('open', () => {
    console.log('DeviceA Connected To Server');
    deviceASocket.send(JSON.stringify({
        type: "registerDevice",
        name: "DeviceA",
        isNode: true,
        inputNames: ["wordInput"],
        outputNames: ["wordOutput"],
        deviceInfo: "Example Device",
    }))
})

deviceASocket.addEventListener("message", (msg) => {
    let data = JSON.parse(msg.data)
    if (data.type === "sendInputs" && data.inputs && data.inputs.wordInput) {
        console.log(`DeviceA received ${data.inputs.wordInput}`)
    } 
})

deviceBSocket.addEventListener('open', () => {
    console.log('DeviceB Connected To Server');
    deviceBSocket.send(JSON.stringify({
        type: "registerDevice",
        name: "DeviceB",
        isNode: true,
        inputNames: ["wordInput"],
        outputNames: ["wordOutput"],
        deviceInfo: "Device B",
    }))
})

deviceBSocket.addEventListener("message", (msg) => {
    let data = JSON.parse(msg.data)
    if (data.type === "sendInputs" && data.inputs && data.inputs.wordInput) {
        console.log(`DeviceB received ${data.inputs.wordInput}`)
    } 
})


// After one second, request the server to connect DeviceA's output to DeviceB's input. 

// NOTE: The link generated by 'requestLink' will become invalid upon device disconnection. For a persistent link
//       that survives disconnection and server power-cycling, utilize `type: 'requestPersistentLink'`.
//       This type of link is established when both devices are online.


setTimeout(() => {
    deviceASocket.send(JSON.stringify({
        type:             "requestLink",
        outputDeviceName: "DeviceA",
        outputName:       "wordOutput",
        inputDeviceName:  "DeviceB",
        inputName:        "wordInput",
    }))
}, 1000)

// Device A continuously sends "Hello, World!" as output, facilitated by the previously established link to device B.

setInterval(() => {
    deviceASocket.send(JSON.stringify({
        type: "sendOutputs",
        outputs: {
        "wordOutput": "Hello, World!",
        },    
    }))
}, 200);
